### ISSUE TITLE
run into error when running the code

### ISSUE THREAD

**Issue by sorobedio** [xiusu/NAS-Bench-Macro#1]
I tried to run your code without any modification.
i just clone it and run the train_benchmark.py file. And it gave me this error.

`lready evaluated.
Evaluating (985/6561): 01100111
Experiment dir : bench-cifar10
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    fh = logging.FileHandler(os.path.join(args.save, 'log', '{}.log'.format(utils.get_real_arch(args.arch))))
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory:`

**Comment by xiusu** [comment]
Thanks for your question.

You can just add the following codes to 39~40 lines in train.py

if not exist os.path.join(args.save, 'log'):
    os.mkdir(os.path.join(args.save, 'log'))

I have updated these codes accordingly.
